AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Backend for site view counter

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.9
    MemorySize: 128
     
Resources:
  ResumeFunction2:
    Type: 'AWS::Serverless::Function'
    Properties:
      
      FunctionName: ResumeFunction2
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Description: Backend for site view counter
      Timeout: 3
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable4
        # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess
      Events:
        ResumeViews:
          Type: Api
          Properties:
            RestApiId: !Ref ResumeViewCountApi
            Path: /counter
            Method: get
        
            
  ResumeViewCountApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'GET'"
        AllowOrigin: "'www.ericnbello.com'"
      # EndpointConfiguration: Regional
      OpenApiVersion: 3.0.1
      StageName: Prod
      
  CounterTable4:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: siteviews
          AttributeType: 'N'
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: siteviews
          KeyType: HASH
      TableName: countertable4